### ISSUE TITLE
Update to serde 1.0

### ISSUE THREAD

**Issue by KodrAus** [benashford/rs-es#108]
See the [release notes](https://github.com/serde-rs/serde/releases/tag/v1.0.0).

It probably just means peppering around some lifetimes and renaming any manually implemented `Visitor`s you might have.

I haven't found a great way to utilise the zero-copyness of `serde` with `hyper` responses because that only works when your data is contiguous and `hyper` will chunk response bodies.

I'm working on upgrading a couple of libraries now so will add this to my pile unless someone else wanted to pick it up :)

cc: @benashford @RoxasShadow

**Comment by benashford** [comment]
Implemented in #109 and released as `0.10.0`
