### ISSUE TITLE
Upgrade Hyper to 0.11

### ISSUE THREAD

**Issue by benashford** [benashford/rs-es#110]
Hyper 0.11 introduces asynchronous processing with Tokio and Futures: https://hyper.rs/guides/client/basic/

We should consider how to modify `rs-es` to use it.  In principal we should adopt Futures as well, this is because ElasticSearch operations can involve non-trivial waiting time, and this would allow application authors to use ElasticSearch without blocking threads, etc.

**Comment by AlexKornitzer** [comment]
Hey, could you bump to this so that rs-es supports openssl 1.1.1? Or does that introduce major breaking changes?

**Comment by AlexKornitzer** [comment]
Ah I see that makes total sense. So when more distros start to push openssl 1.1.1, the only solution will be to use futures? As by looking at it there is no easy way to just bump the openssl cargo.

**Comment by benashford** [comment]
It looks that way, looking at the later releases of hyper.  The default path would be to use hypertls rather than hyper-openssl, which in turn uses native-tls which will use the latest openssl on Linux platforms.  But hypertls was only introduced after Hyper 0.11, the first release to be Futures based.

To support newer versions of openssl with Hyper 0.10 we'd need a different connector that supported that version of Hyper.  But I'm not aware of any.

**Comment by benashford** [comment]
Closing this issue as #126 means we're using Hyper 0.12 indirectly via Reqwest.
