### ISSUE TITLE
Refreshing index not working

### ISSUE THREAD

**Issue by biot023** [benashford/rs-es#118]
Hi -- in order to have my tests run I regularly call refresh on the client.
The hope is that doing so will commit any changes I've made that I'm relying on -- for instance a document being created or all documents being deleted.
This testing approach has worked when I've used ElasticSearch in other languages -- namely Ruby and JavaScript.
However I'm getting intermittent failures in my tests where the index should be refreshed and up-to-date with the data I expect it to have.
By way of debugging I've put a sleep delay of 1500 ms in there after the call to `refresh()` and before the assertion but that hasn't stopped the intermittent error that occurs there.
So I thought I should check here to be sure that refreshing the index is supposed to work in the manner I expect it to?
Thanks for any and all advice,
   Doug.

**Comment by biot023** [comment]
No, I'm afraid that's still not working.
My `delete_all()` method now uses the scan-and-bulk approach and I'm calling `refresh()` on the index before I issue it as well as afterwards.
Should refreshing the index be working in the manner I expect, at least in principle?
By which I mean: should it be flushing all operations to the index so that my next query should be to a full and complete dataset?
I'm pretty stumped for the time being unless some inspiration strikes.
Thanks again for any insight anyone can offer,
   Doug.

**Comment by benashford** [comment]
Hello,

Yes `refresh` should work in the way you intend.  Most of the tests for this library do the same thing: create some data, call `refresh`, then query that data.  It's a standard part of the API, so there's no reason why `rs-es` would be behaving differently than other libraries.

Do you have a minimal test-case that fails?

Thanks

**Comment by biot023** [comment]
Ah, then I have some digging, debugging and refactoring to do!
Unfortunately I haven't anything that fits in a simple test-case atm.
I shall investigate... Cheers, @benashford .

**Comment by biot023** [comment]
Hi again @benashford 
It turns out the answer is the same one it always is -- I'm an idiot!
I remember reading the docs on testing in Rust and I remember thinking "that's interesting, I'll remember that" when I read the bit about tests running in parallel.
Then I promptly forgot it.
So running `cargo test -- --test-threads=1` fixed it, of course.
Sigh.
Thanks again for your advice!
   Doug.

**Comment by benashford** [comment]
No problem, I'm happy that it's sorted :)
