### ISSUE TITLE
Improving geo_shape query

### ISSUE THREAD

**Issue by antoine-de** [benashford/rs-es#129]
Hi,

The [`GeoShapeQuery`](https://docs.rs/rs-es/0.11.1/rs_es/query/geo/struct.GeoShapeQuery.html) handle for the moment only a `LineString` shape (a `Vec<(f64, f64)>`)

I think it would be better to take a [geojson](https://github.com/georust/geojson/) object since it would handle all the scenario (and it will be trivially serialized to es).

Would it be ok for you if we add a [geojson](https://github.com/georust/geojson/) dependency to handle this ? We could also add our own enum to handle all the shape types but it would be more difficult to maintain and use from external projects

**Comment by benashford** [comment]
Hello.

Yes, that does make sense.

My only concern is adding specific dependencies for something many users won't actually use. Perhaps we could put it behind a feature flag?

I'm not sure exactly where the boundary should be set, perhaps a `geo` flag with enables all the ES geo queries and includes the `geojson` dependency, and we could make the default build leave the geo queries out?

**Comment by kinnou02** [comment]
A feature flag enabling all geojson queries seems good, most ES queries doesn't use geojson, at this time I only known `geoshape`. So this flag will only enable [GeoShapeQuery](https://docs.rs/rs-es/0.11.1/rs_es/query/geo/struct.GeoShapeQuery.html) on non indexed shape, so it will still be possible to make query on `[IndexedShape](https://docs.rs/rs-es/0.11.1/rs_es/query/geo/struct.IndexedShape.html)` without the flag set.
