### ISSUE TITLE
Replace rustc_serialize with Serde

### ISSUE THREAD

**Issue by benashford** [benashford/rs-es#23]
Serde is being pitched as the replacement for rustc_serialize.

**Comment by KodrAus** [comment]
This would be awesome for me, because it would allow me to interop the type mapping work I've been doing with `rs-es`

**Comment by benashford** [comment]
This is now in `master`, and I'll release it as part of 0.3.0 when all the other bits are ready.  0.3.0 is going to have minor breaking changes anyway, due to it lifting the baseline ES version to 2.0, so I may as well bundle all the breaking changes together.

**Comment by benashford** [comment]
Released as v0.3.0
