### ISSUE TITLE
Miscellaneous build failures on latest Rust, and even more on nightly

### ISSUE THREAD

**Issue by benashford** [benashford/rs-es#5]
Investigate and fix...

**Comment by KodrAus** [comment]
How's this coming along?

**Comment by benashford** [comment]
@KodrAus I've just pushed a fix.  The head of master and the 0.2.0 release on crates.io should now build with the latest Rusts.

**Comment by benashford** [comment]
Now fixed.  The problem was this crate implemented a conversion trait for boxed versions of two types.  Core rust (in the `alloc` crate) added the same thing, hence the conflict.  I've removed the one from `rs-es`, but this means the latest `rs-es` will no longer build against earlier Rusts.

**Comment by KodrAus** [comment]
Ah great, thanks :)
