### ISSUE TITLE
Support for Elasticsearch 2.x

### ISSUE THREAD

**Issue by KodrAus** [benashford/rs-es#6]
Do you have plans to support Elasticsearch 2.x? There are a bunch of [changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-2.0.html), but it'd be good to be able to run against the latest version.

**Comment by benashford** [comment]
Yes.  Bringing it up to the latest ElasticSearch is the goal.  But I can't really say how long it is likely to take at this stage.

**Comment by benashford** [comment]
The baseline has been brought up to ElasticSearch 2.0, and released as `rs-es` v0.3.0.

There are still a number of unimplemented features however, these will be expanded upon and implemented as specific changes.
