### ISSUE TITLE
could not compile with serde_macros depdendency

### ISSUE THREAD

**Issue by timglabisch** [benashford/rs-es#64]
please take a look at https://github.com/serde-rs/quasi/issues/35#issuecomment-202404870 i've exacly the same problem, but couldn't solve this by using

[dependencies.rs-es]
version =  "0.3.2"
features = ["nightly_without_ssl"]

**Comment by benashford** [comment]
Hello,

I haven't been able to reproduce this problem, testing it with a blank project with that configuration.  Could you provide more information, specifically: the version of `rustc`, the full `Cargo.toml` file, and the full error message?  Also which OS is it being built on (I'm currently testing it on Ubuntu).

Thanks

**Comment by timglabisch** [comment]
i try to use it in this project: https://github.com/timglabisch/rustinvoice (316a347f2651512d4c89b5ed935b31d5949dc9a7)

on OSX Yosemite 10.10.5 with rustc 1.10.0-nightly (b5ba5923f 2016-04-21)

i just added

```
[dependencies.rs-es]
version = "0.3.2"
features = ["nightly_without_ssl"]
```

to the toml file:




```
rustinvoice git:(master) ✗ cargo run
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading lazy_static v0.2.1
 Downloading gcc v0.3.28
   Compiling gcc v0.3.28
   Compiling lazy_static v0.2.1
   Compiling quasi v0.9.0
   Compiling aster v0.15.0
   Compiling openssl-sys-extras v0.7.10
   Compiling openssl v0.7.10
   Compiling quasi_codegen v0.9.0
   Compiling serde_codegen v0.7.2
   Compiling quasi_macros v0.9.0
/Users/tim/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/quasi_macros-0.9.0/src/lib.rs:19:29: 19:32 error: mismatched types:
 expected `&mut syntex::Registry`,
    found `&mut rustc_plugin::Registry<'_>`
(expected struct `syntex::Registry`,
    found struct `rustc_plugin::Registry`) [E0308]
/Users/tim/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/quasi_macros-0.9.0/src/lib.rs:19     quasi_codegen::register(reg);
                                                                                                                                                     ^~~
/Users/tim/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/quasi_macros-0.9.0/src/lib.rs:19:29: 19:32 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: Could not compile `quasi_macros`.
```

**Comment by benashford** [comment]
Cool, thanks for this.

I think there are multiple issues here.  At the moment, there is a different issue with Quasi and the latest Rust nightlies.  Once that is fixed (there's a PR being merged at the moment), I'll update `rs-es` too once all the dependencies are on crates.io.  I'll use this example as a test case for the new version.

In the meantime everything should work with Stable or Beta Rust releases.  Although, of course, developing things that use Serde is easier with the nightlies.

**Comment by benashford** [comment]
This is currently dependent on #65

**Comment by benashford** [comment]
The upstream issues have been fixed and released.  If you use the `0.3.4` version of `rs-es` and a recent Rust nightly everything should be good.

```
[dependencies.rs-es]
version = "0.3.4"
features = ["nightly_without_ssl"]
default-features = false
```
