### ISSUE TITLE
Re-enable Nightly

### ISSUE THREAD

**Issue by benashford** [benashford/rs-es#65]
The Nightly Travis build is currently disabled due to an issue with an upstream dependency (Serde, in particular Quasi) being built on Nightly.

We should upgrade the dependency as soon as a fix is available, and re-enable the nightly build.

**Comment by benashford** [comment]
This is currently blocked by: https://github.com/serde-rs/serde/issues/305

**Comment by dtolnay** [comment]
0.7.5 has been published with the fix.

**Comment by benashford** [comment]
@dtolnay that's brilliant, thanks for all your work looking into this.

Nightly is building again 👍

**Comment by benashford** [comment]
Merged in #70

**Comment by benashford** [comment]
Released v0.3.4 containing this.
