### ISSUE TITLE
the trait core::convert::From<rs_es::query::BoolFilter> is not implemented for the type Box<rs_es::query::Filter>

### ISSUE THREAD

**Issue by RoxasShadow** [benashford/rs-es#8]
**Code**
```rust
use rs_es::Client;
use rs_es::operations::search::{Sort, SortField, Order};
use rs_es::query::{Filter, Query};

// [...]
fn main() {
  // [...]

  // I'm just trying to compile this, it's the snippet inside the README 
  let query = Query::build_filtered(
    Filter::build_bool()
      .with_must(vec![
        Filter::build_term("field_a", "value").build(),
        Filter::build_range("field_b")
          .with_gte(5)
          .with_lt(10)
          .build()
      ])
  )
  .with_query(Query::build_query_string("some value").build())
  .build();

  let result = es.search_query()
    .with_indexes(ES_INDEXES)
    //.with_query(&Query::build_match_all().build())
    .with_query(&query)
    .with_sort(&Sort::new(vec![
      SortField::new("updated_at", Some(Order::Desc)).build()
    ]))
    .send()
    .ok()
    .unwrap();
}
```

**Error**
>
src/main.rs:26:15: 26:36 error: the trait `core::convert::From<rs_es::query::BoolFilter>` is not implemented for the type `Box<rs_es::query::Filter>` [E0277]
src/main.rs:26   let query = Query::build_filtered(
                             ^~~~~~~~~~~~~~~~~~~~~
src/main.rs:26:15: 26:36 help: run `rustc --explain E0277` to see a detailed explanation
src/main.rs:26:15: 26:36 note: required by `rs_es::query::Query::build_filtered`
error: aborting due to previous error
Could not compile `sample`.
>
Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name sample --crate-type bin -g --out-dir /Users/giovanni/Desktop/sample/target/debug --emit=dep-info,link -L dependency=/Users/giovanni/Desktop/sample/target/debug -L dependency=/Users/giovanni/Desktop/sample/target/debug/deps --extern postgres=/Users/giovanni/Desktop/sample/target/debug/deps/libpostgres-2680c17c75628e6e.rlib --extern rustc_serialize=/Users/giovanni/Desktop/sample/target/debug/deps/librustc_serialize-79a17eda1cd94e46.rlib --extern rs_es=/Users/giovanni/Desktop/sample/target/debug/deps/librs_es-5ee9d634caeceacd.rlib --extern postgres_array=/Users/giovanni/Desktop/sample/target/debug/deps/libpostgres_array-06c7843d8da23f1e.rlib -L native=/Users/giovanni/Desktop/sample/target/debug/build/openssl-09576f2f9776fa80/out -L native=/Users/giovanni/Desktop/sample/target/debug/build/openssl-sys-extras-52d5315fb71d3c6d/out` (exit code: 101)

**Platform**
*Machine*
> Darwin lifestream.Speedport_W723_V_Typ_A_1_01_011 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64

*ES*
> Version: 2.1.1, Build: 40e2c53/2015-12-15T13:05:55Z, JVM: 1.8.0_66

*Rust*
> rustc 1.6.0

*rs-es*
Both 0.2 and *master*

**Comment by benashford** [comment]
Thanks for this.  This was an error in the example in the README, there was a `.build()` missing.

It should have said:

```rust
let query = Query::build_filtered(
                Filter::build_bool()
                    .with_must(vec![Filter::build_term("field_a",
                                                       "value").build(),
                                    Filter::build_range("field_b")
                                        .with_gte(5)
                                        .with_lt(10)
                                        .build()])
                    .build())
                .with_query(Query::build_query_string("some value").build())
                .build();
```

I've updated the README too.
